### PR TITLE
Line length consensus

### PR DESCRIPTION
**Pull request by hurtstotouchfire**
I'm not attached to 120, but whatever it is, we should consense and then be consistent.

### CODE REVIEW

**Comment by vhladama** [comment]
can you also update the rubocop yml file to match please?

**Comment by davexunit** [comment]
120 is too long to be easily readable, especially in git logs.  80 is
pretty much the "just right" number.  The precise number 80 has its
roots in history as it was the line length of IBM punch cards and also
the line length of teletype terminals.  However, the rationale for
this number isn't simply a historical argument from tradition.  Long
lines are widely agreed upon to be hard to read.  Typographers
recommend keeping lines short for maximum readability:

```
Shorter lines are more comfortable to read than longer lines. As
line length increases, your eye has to travel farther from the end
of one line to the beginning of the next, making it harder to
track your progress vertically.
```

See: http://practicaltypography.com/line-length.html

See also:
- http://programmers.stackexchange.com/questions/604/is-the-80-character-limit-still-relevant-in-times-of-widescreen-monitors
- https://en.wikipedia.org/wiki/Column_%28typography%29
- https://en.wikipedia.org/wiki/Line_length

**Comment by estebanz01** [comment]
I prefer the 120 length limit. There's a bunch of people arguing why 80 or 120, but this comment does an interesting analysis: https://github.com/bbatsov/ruby-style-guide/issues/207#issuecomment-24459812, 

I prefer the 120 'cause:

> 125 characters per line is the real de facto coding standard for maximum line length these days, because this is the maximum number of characters that you can see in the GitHub diff view. This used to be 119 characters, but the page layout changed.

**source:** http://hilton.org.uk/blog/source-code-line-length

Also, I agree with the following statement (I think 80 length limit is aggressive):

> On the other hand the problem with aggressive line length limits is that they often come at the expense of code readability – programmers start using less descriptive variable and method names, span long expressions over multiple lines, etc. A balance has to struck somewhere.

**source**: http://batsov.com/articles/2013/06/26/the-elements-of-style-in-ruby-number-1-maximum-line-length/

Finally, but not less important, I think we can't compare the source code line with a book/magazine/paper line, 'cause every line of code is, in theory, standalone:

> Lines of code are of highly variable widths where each line (typically) is a standalone concept, related to those around them like sentences in a paragraph, but I've never seen in poetry or prose a limit placed on the number of characters allowed in a sentence. 

**source:** https://github.com/bbatsov/ruby-style-guide/issues/207#issuecomment-23567988

**Comment by alboyadjian** [comment]
I like the thought and research you've put into this.  Thank you.  This doesn't make it any easier to come to consensus, as it seems like we're just seeing more and more good arguments for both sides.

If we were to split the difference, promote 80 as optimum, and enforce 100 as our standard, would that leave you, @davexunit in a state where your editor can't cleanly display lines of other people's code?

Can we configure our editors and/or rubocop to warn after exceeding 80?

When I use vim to edit a git commit, once I pass 50 characters of line length, all the additional characters change color.  Once I cross 72, any additional characters turn danger-red.  Not saying we want to fusk up our syntax highlighting like this, but I think there's other ways we can achieve the same goals.

**Comment by hurtstotouchfire** [comment]
It sounds like we like 72 chars? Shall I change it to that?

**Comment by hurtstotouchfire** [comment]
It sounds like we're still split on this. @estebanz01 would you care to follow up? I prefer 120 as well.

**Comment by davexunit** [comment]
Not 72, 80.

**Comment by tille** [comment]
I'd prefer 80 characters per line.
however I agree with Adam in promote 80 as optimum, and enforce 100 as our standard.

**Comment by wksmall** [comment]
I like 120 as a max but I could live with 100. 80 should be optimal.

**Pull request merged**
